### ISSUE TITLE
QueryFailedError: column cnst.consrc does not exist

### ISSUE THREAD

**Issue by GopherJ** [node-casbin/typeorm-adapter#15]
It works fine on my Ubuntu laptop, but while I move to deepin, I got a strange error message while all the dependencies have been correctly installed and the connection between the host and the postgres database is ok.

Here what I got while I just cloned this repo and changed the options:

`code`
```
 const a = await TypeORMAdapter.newAdapter({
        type: 'postgres',
        host: '127.0.0.1',
        port: 5432,
        username: 'test',
        password: 'test2019',
        database: 'test',
    });
```

`error message` while executing `npm run test`
```
QueryFailedError: column cnst.consrc does not exist
```

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@GopherJ see: https://github.com/typeorm/typeorm/issues/4573

It seems that you should use another version of PostgreSQL.

**Comment by GopherJ** [comment]
@hsluoyz  thanks, let me try, I tried already PostgreSQL@latest (12) and PostgreSQL@11, but maybe 11.5 will work

**Comment by GopherJ** [comment]
@hsluoyz while I test again, it works for `PostgreSQL@11`
