### ISSUE TITLE
Promise Error

### ISSUE THREAD

**Issue by judahb** [node-casbin/typeorm-adapter#2]
(node:42385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hsluoyz** [comment]
@judahb , [the test](https://github.com/node-casbin/typeorm-adapter/blob/master/test/adapter.test.ts) has passed in Travis: https://travis-ci.org/node-casbin/typeorm-adapter for Node 11.4, Node 8 and Node 6. It uses the same code as README. Please run that test file and provide the result here.

**Comment by hsluoyz** [comment]
Closed as stale. Feel free to re-open if still exists.
