### ISSUE TITLE
[feat] pass connection object to newAdapter

### ISSUE THREAD

**Issue by onichandame** [node-casbin/typeorm-adapter#26]
A common practice in building stateful apps is to reuse the same database connection across different functionalities, e.g. logging, authentication, authorisation, etc.

An intuitive approach to ensure that all modules have the same database connection is to initialize the connection somewhere outside of all other modules and to pass the one connection object to them.

However the `TypeORMAdapter.newAdapter`, as stated in the README, only receives the connection options. It would be nice and more consistent with other modules if it can accept the connection object instead.

**Comment by hsluoyz** [comment]
@onichandame great idea. Can you make a PR to add a new constructor to accept conn as arg?

**Comment by onichandame** [comment]
I will submit it when tests have passed.
