### ISSUE TITLE
this.adapter.loadPolicy is not a function

### ISSUE THREAD

**Issue by Shaun-Li** [node-casbin/typeorm-adapter#3]
use as example，just add in middleware, but get a nodejs.TypeError

nodejs.TypeError: this.adapter.loadPolicy is not a function
    at Enforcer.<anonymous> (E:\workSpace\typeorm_test\node_modules\casbin\lib\coreEnforcer.js:140:32)

**Comment by nodece** [comment]
Can you provide a runnable example?

**Comment by Shaun-Li** [comment]
> Can you provide a runnable example?

Sorry, picture upload failed. 

This is some code in config.default.ts:
config.middleware = ['user','authz'];
  config.authz = {
    enable: true,
    newEnforcer: async() => {
      const dbConnect = TypeORMAdapter.newAdapter({
        "type": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": "123456",
        "database": "casbin"
      });
      const enforcer = await Enforcer.newEnforcer('authz_model.conf', dbConnect);
      return enforcer
    }
  }

router.ts：
  router.get('/test', controller.home.test);

controller/home.ts：
  router.get('/test', controller.home.test);

**Comment by nodece** [comment]
Use node-casbin v2.0, you can try this
```
import casbin from 'casbin';
const enforcer = await casbin.newEnforcer('authz_model.conf', dbConnect);
return enforcer
```

**Comment by Shaun-Li** [comment]
@nodece 
use “ import casbin from 'casbin'; ” has error：
Module '"E:/workSpace/typeorm_test/node_modules/casbin/lib/index"' has no default export.

**Comment by nodece** [comment]
ts use ```import * as casbin from 'casbin';```

**Comment by Shaun-Li** [comment]
@nodece 
done as you said，still has “this.adapter.loadPolicy is not a function”......

**Comment by Shaun-Li** [comment]
> @nodece
> done as you said，still has “this.adapter.loadPolicy is not a function”......

I use 
const dbConnect = await SequelizeAdapter.newAdapter('mysql://root:123456@localhost:3306/');
is ok；but const dbConnect = TypeORMAdapter.newAdapter(......)  can't

**Comment by nodece** [comment]
`TypeORMAdapter.newAdapter` return is `Promise`, you forget use `await`.

**Comment by Shaun-Li** [comment]
> `TypeORMAdapter.newAdapter` return is `Promise`, you forget use `await`.

oh my god!!!
I am so sorry.
thank you very much!!
