### ISSUE TITLE
Publish v1.3.0 to npm

### ISSUE THREAD

**Issue by cmac** [node-casbin/typeorm-adapter#33]
Could you publish the latest version (v1.3.0) to npm?
Thanks

**Comment by hsluoyz** [comment]
@Zxilly plz fix the CI error and then release v1.3.0.

![image](https://user-images.githubusercontent.com/3787410/111878074-8790e900-89e1-11eb-83bd-178cffda9a82.png)

**Comment by Zxilly** [comment]
working on this

**Comment by Zxilly** [comment]
@cmac have release v1.3.0 at https://www.npmjs.com/package/typeorm-adapter/v/1.3.0
@hsluoyz CI seems fine. Last commit https://github.com/node-casbin/typeorm-adapter/commit/8b25445c5c962094215cd13d62058ee5fa345c35 happens on 12 Nov 2020. After that travis.org migrated to travis.com. Another commit will make it ok.

**Comment by hsluoyz** [comment]
@Zxilly don't forget our rules. Please also release at GitHub Actions: https://github.com/node-casbin/typeorm-adapter/releases

For CI, please update CI badge if we are using Travis-ci.com now. But finally we will migrate to GitHub Actions.

**Comment by hsluoyz** [comment]
@Zxilly I have updated the badge, it seems that we are running out of Travis-ci.com quota again. Plz migrate to GitHub Actions now.

**Comment by Zxilly** [comment]
@hsluoyz I didn't have permission to make a release in this repo.

**Comment by hsluoyz** [comment]
@Zxilly please try again.

**Comment by hsluoyz** [comment]
@cmac released: https://github.com/node-casbin/typeorm-adapter/releases/tag/v1.3.0
