### ISSUE TITLE
No repository for "CasbinRule" was found.

### ISSUE THREAD

**Issue by tankorbox** [node-casbin/typeorm-adapter#4]
I added casbin typeorm-adapter into my existing project which has already a typeorm mssql conenction. An error occured: "No repository for "CasbinRule" was found. Looks like this entity is not registered in current "default" connection?" Please help me or give some solutions. Thank you so much!

**Comment by hsluoyz** [comment]
You should use a new connection.

**Comment by tankorbox** [comment]
> You should use a new connection.

Hi bro. how can i create a new connection? I thought that typeorm-adapter created an seperated connection.

**Comment by hsluoyz** [comment]
@nodece @Chalin-Shi

**Comment by nodece** [comment]
Can you provide some code about this issue?

**Comment by dreamdevil00** [comment]
same issue

**Comment by dreamdevil00** [comment]
It seems that when multiple connections exist,  the CasbinRule entity failed to grap `usedConnection`, and fall back to "default" connection

[typeorm code](https://github.com/typeorm/typeorm/blob/0e705b7c2962de57db93085d83c3c7bff2a7b1d1/src/repository/BaseEntity.ts#L85)

```javascript
loadPolicy(model) {
    return __awaiter(this, void 0, void 0, function*() {
     // this line solves the problem as a walkaround
    // but how could the problem happened
      casbinRule_1.CasbinRule.useConnection(this.typeorm);
      const lines = yield casbinRule_1.CasbinRule.find();
      for (const line of lines) {
        this.loadPolicyLine(line, model);
      }
    });
  }
```

**Comment by nodece** [comment]
It has been fixed and published new version to npm.

**Comment by hsluoyz** [comment]
@nodece great work!
