### ISSUE TITLE
Limited to 6 policy arguments

### ISSUE THREAD

**Issue by harveyappleton** [node-casbin/typeorm-adapter#41]
Hi there,

Thanks for an awesome library! 
Just a quick thought. Noticed in the src that a policy can only have up to 6 arguments (v0, v1, v2, v3, v4, v5) - [https://github.com/node-casbin/typeorm-adapter/blob/master/src/casbinRule.ts#L18](url)

We're using 7 for our Casbin implementation. 
Is there any chance we could perhaps increase the number of arguments you can persist in the database?

Thanks!

**Comment by hsluoyz** [comment]
@harveyappleton I think 7 is OK. Can you make a PR to increase it?

**Comment by harveyappleton** [comment]
@hsluoyz Sure thing! will do
