### ISSUE TITLE
v1.5 Performance regression

### ISSUE THREAD

**Issue by jkalberer** [node-casbin/typeorm-adapter#49]
Hi, I updated to 1.5 after this PR and it seems like there is a huge perf regression in this framework.

I'm essentially doing this:
```
enforcer = await newEnforcer(join(__dirname, '../model.conf'), this.adapter);
await enforcer.addNamedMatchingFunc(GROUP_TYPE, globMatch);
await enforcer.addNamedDomainMatchingFunc(GROUP_TYPE, globMatch);
await enforcer.loadFilteredPolicy({
  v0: subjectIdentifier, // load only what's needed for this user
});

const roles = await enforcer.getRolesForUser(subjectIdentifier);
await Promise.all(roles.map(async (role) => enforcer?.loadIncrementalFilteredPolicy({ v0: role })));
```
Then when I call `enforcer.enforce(subjectIdentifier, domain, object, action);` the process hangs.

For more context, I have ~5500 policies + groups but it should be able to handle that.

---

I know that many of the patterns in the new TypeORM have moved away from the singleton patterns like `getRepository` and other helper functions. I think you need to work with the Typeorm connection instance instead of using helpers like this - https://github.com/node-casbin/typeorm-adapter/blob/master/src/adapter.ts#L115

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 plz take a look

/cc @nodece @Zxilly

**Comment by jkalberer** [comment]
I figured this out. The `find` function in the adapter is being passed an `object` so the typechecking doesn't catch the issue. https://github.com/node-casbin/typeorm-adapter/blob/master/src/adapter.ts#L126-L130

It needs to be `find({where: filter})` in order to make this work.

I have fixed it in this PR but I do a lot more like removing deprecated APIs.  https://github.com/node-casbin/typeorm-adapter/pull/52
