### ISSUE TITLE
assign user specific rule

### ISSUE THREAD

**Issue by GopherJ** [node-casbin/typeorm-adapter#5]
hello, I found that I'm able to save a policy by using:
```
    await e.addPolicy('admin', 'domain1', '/data0', '*');
```

but how can I put a user in this group (`admin of domain1`)?

**Comment by GopherJ** [comment]
```
    await e.addPolicy('p', 'admin', 'domain1', '/data0', '*');
```
this doesn't work

**Comment by nodece** [comment]
Add `admin` user to `admin1` role:
```
await e.addGroupingPolicy("admin",'domain1')
```

**Comment by GopherJ** [comment]
thanks @nodece  for your quick reply, I just realized that we have other api for doing this so we don't need to stick to `addPolicy` ~

I found this:
 `await e.addRoleForUser('alice', 'admin', 'domain1');`

which solved my problem
