### ISSUE TITLE
use ExistentConnection

### ISSUE THREAD

**Issue by nobu121** [node-casbin/typeorm-adapter#50]
how can i use the ExistentConnection?

```node
  const conn = getConnection();

  const adapter = await TypeORMAdapter.newAdapter({
      connection: conn,
  });
```

but i got  `No metadata for "CasbinRule" was found.`

please help me, thanks!

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 

/cc @nodece @Zxilly

**Comment by Shivansh-yadav13** [comment]
I have not used this adapter before, but maybe you need to use the trick written in the test:
https://github.com/node-casbin/typeorm-adapter/blob/master/test/existent-connection-adapter.test.ts
https://github.com/node-casbin/typeorm-adapter/blob/db31e4e32e9e6664efa515d0700043e960bf6664/test/existent-connection-adapter.test.ts#L55

**Comment by jkalberer** [comment]
You need to initialize your DB connection (wherever you pass in your credentials) with a `entities: [CasbinRule]`. There might also be an API to add the metadata afterwords. Another thing is that you need to add a migration or set `synchronize=true` on your connection in order for the casbin rule table to be added to the database.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13

**Comment by hsluoyz** [comment]
Closed as resolved
