### ISSUE TITLE
[bug] removeFilteredPolicy is not working properly

### ISSUE THREAD

**Issue by andrewboxonko** [node-casbin/typeorm-adapter#57]
Once I want to delete filtered policies and skip some columns I will do something like that
```
[
    [alice, data, read],
    [alice, data1, read],
    [alice, data1, write]
]
```

```typescript
enforcer.removeFilteredPolicy(0, 'alice', '', 'read')
```
so I expect those policies to be deleted
```
[alice, data, read],
[alice, data1, read],
```

```typescript
await this.getRepository().delete({
      ...line,
});
```
on that line, typeorm adapter makes a deletion of policies
the `line` looks like this
```
{
    v0: 'alice',
    v1: '',
    v2: 'read'
}
```

as a result, rows won't be deleted because there is no rows for which v1 = ''

**Comment by hsluoyz** [comment]
@voile-source
