### ISSUE TITLE
Issue: ObjectID no longer be used in typeorm, please update to ObjectId

### ISSUE THREAD

**Issue by natnt2000** [node-casbin/typeorm-adapter#65]

**Comment by natnt2000** [comment]
Issue in casbinMongoRule.ts file.

**Comment by hsluoyz** [comment]
@natnt2000

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/node-casbin/typeorm-adapter/commit/9dfa7c8dd1d1f5e03d2e0fb42118c0d73504d736 , use latest v1.6.0 version
