### ISSUE TITLE
The lib directory is missing in version 1.6.0

### ISSUE THREAD

**Issue by lichangwei** [node-casbin/typeorm-adapter#68]
Error: Cannot find module '/app/node_modules/typeorm-adapter/lib/index.js'. Please verify that the package.json has a valid "main" entry

![image](https://github.com/node-casbin/typeorm-adapter/assets/718802/4d22a0d6-58ab-40f1-89a4-0dada69b52cd)

**Comment by hsluoyz** [comment]
@lichangwei can you try 1.6.1? https://www.npmjs.com/package/typeorm-adapter/v/1.6.1
