### ISSUE TITLE
don't overwrite casbin_rule if table exists already

### ISSUE THREAD

**Issue by GopherJ** [node-casbin/typeorm-adapter#8]

**Comment by hsluoyz** [comment]
Can you be more specific?

**Comment by nodece** [comment]
@GopherJ We should use `typeorm` to synchronize `casbin_rule`.
If `typeorm-adapter` cannot meet your needs,  you can create own adapter.

**Comment by GopherJ** [comment]
hello @hsluoyz @nodece , sure it meets my needs, I was wondering if it overwrites `casbin_rule` even it exists already, because I added some CONTRAINT to this table to meet my needs.

Also my situation is that I have a casbin server with some management apis, I use postgresql for storing the policies, yesterday I was trying to add a new function to read `policy.csv` while starting or restarting, but if I restart this server, it duplicates my default policies...

```js
 enforcer.addPolicy(addPrefix(role), domain, object, action).catch(console.error);
```

I think it should be related to casbin cache ? I'm not sure.

So I tried to create `casbin_rule` manually using `diesel`, and I added some constraints to `casbin_rule` table, but it seems it doesn't help...

```
// rbac with domain
CONSTRAINT unique_key UNIQUE(ptype, v0, v1, v2, v3)
```

**Comment by nodece** [comment]
@GopherJ 
My Solution:
Please check manually whether the table exists then set `synchronize` in typeorm option.

**Comment by GopherJ** [comment]
@nodece my setup script will garantee that this table exists (it will be created by diesel), so I need to set `synchronize: false` right?

**Comment by nodece** [comment]
@GopherJ Right!

**Comment by GopherJ** [comment]
@nodece thanks!
